image: debian:12

stages: # List of stages for jobs, and their order of execution
    - python_lint
    #- sonar_check

sonarqube-check:
    image:
        name: sonarsource/sonar-scanner-cli:latest
        entrypoint: [""]
    stage: sonar_check
    needs: []
    variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
        GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .sonar/cache
    script:
        - sonar-scanner
    allow_failure: false
    rules:
        - if: $CI_COMMIT_BRANCH == 'main'

python-lint-job:
    stage: python_lint
    needs: []
    allow_failure: false
    image: python:3.11-bookworm

    script:
        - pip install pipenv -U --quiet
        - pipenv install --dev
        - pipenv run lint
