select = [
    "A",
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "COM",
    "DTZ",
    "E",
    "F",
    "FBT",
    "FLY",
    "PTH",
    "I",
    "ICN",
    "ISC",
    "N",
    "PERF",
    "PL",
    "PYI",
    "Q",
    "RET",
    # "T20", # todo activate
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "PT",
    "SLOT",
    "TCH",
    "UP",
    "YTT",
    "T10",
    "PIE",
    "INP",
    "G",
    "EM",
    "EXE",
    "FA",
    "TID",  # maybe disable,
    "INT",
    "TD",
    "FIX",
    "ERA",
    "PGH",
    "TRY",


]


# Never enforce `E501` (line length violations).
# PLR2004 =>  magic-value-comparison 
# PLR0913 =>  too-many-arguments
# PLR0911 =>  too-many-return-statements 
# PLR0912 =>  too-many-branches 
# UP007   =>  non-pep604-annotation  (Union[a,b] => a|b is fine, but i like Optional[a] better then a|None)
# ANN401  =>  any-type 
ignore = ["E501", "PLR2004", "PLR0913", "PLR0911", "PLR0912", "UP007", "ANN401"]

# 88 (standard) is to small
line-length = 100

# Target Python version is 3.11.
target-version = "py311"

[per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files
"__init__.py" = ["E402"]

# ignore "INP001" (implicit namespace package) for all files in src/
"classifier.py" = ["INP001"]
"entry.py" = ["INP001"]
"main.py" = ["INP001"]
