from typing import Annotated

from attr import dataclass

from content.language import (
    Alpha2LanguageStr,
    Alpha3LanguageStr,
    ExactLen,
    LongLanguageStr,
)
from helper.classifier import LinearCoeffs, MemoryPatternLinear, Model

__all__: list[str] = ["voxlingua107_ecapa_model"]

voxlingua107_ecapa_languages_count = 107


# NOTE:
# Warning: In the dataset and in the defaults of this model (see label_encoder.txt, the used ISO language code for Hebrew is obsolete (should be he instead of iw). The ISO language code for Javanese is incorrect (should be jv instead of jw). See issue #2396. (https://github.com/speechbrain/speechbrain/issues/2396)
voxlingua107_ecapa_languages: Annotated[
    list[tuple[Alpha2LanguageStr | Alpha3LanguageStr | str, LongLanguageStr]],
    ExactLen(voxlingua107_ecapa_languages_count),
] = [
    (
        Alpha2LanguageStr.from_str_unsafe("ab"),
        LongLanguageStr("Abkhazian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("af"),
        LongLanguageStr("Afrikaans"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("am"),
        LongLanguageStr("Amharic"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ar"),
        LongLanguageStr("Arabic"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("as"),
        LongLanguageStr("Assamese"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("az"),
        LongLanguageStr("Azerbaijani"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ba"),
        LongLanguageStr("Bashkir"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("be"),
        LongLanguageStr("Belarusian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("bg"),
        LongLanguageStr("Bulgarian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("bn"),
        LongLanguageStr("Bengali"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("bo"),
        LongLanguageStr("Tibetan"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("br"),
        LongLanguageStr("Breton"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("bs"),
        LongLanguageStr("Bosnian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ca"),
        LongLanguageStr("Catalan"),
    ),
    (
        Alpha3LanguageStr.from_str_unsafe("ceb"),
        LongLanguageStr("Cebuano"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("cs"),
        LongLanguageStr("Czech"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("cy"),
        LongLanguageStr("Welsh"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("da"),
        LongLanguageStr("Danish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("de"),
        LongLanguageStr("German"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("el"),
        LongLanguageStr("Greek"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("en"),
        LongLanguageStr("English"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("eo"),
        LongLanguageStr("Esperanto"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("es"),
        LongLanguageStr("Spanish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("et"),
        LongLanguageStr("Estonian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("eu"),
        LongLanguageStr("Basque"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("fa"),
        LongLanguageStr("Persian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("fi"),
        LongLanguageStr("Finnish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("fo"),
        LongLanguageStr("Faroese"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("fr"),
        LongLanguageStr("French"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("gl"),
        LongLanguageStr("Galician"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("gn"),
        LongLanguageStr("Guarani"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("gu"),
        LongLanguageStr("Gujarati"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("gv"),
        LongLanguageStr("Manx"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ha"),
        LongLanguageStr("Hausa"),
    ),
    (
        Alpha3LanguageStr.from_str_unsafe("haw"),
        LongLanguageStr("Hawaiian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("hi"),
        LongLanguageStr("Hindi"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("hr"),
        LongLanguageStr("Croatian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ht"),
        LongLanguageStr("Haitian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("hu"),
        LongLanguageStr("Hungarian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("hy"),
        LongLanguageStr("Armenian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ia"),
        LongLanguageStr("Interlingua"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("id"),
        LongLanguageStr("Indonesian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("is"),
        LongLanguageStr("Icelandic"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("it"),
        LongLanguageStr("Italian"),
    ),
    (
        "iw",
        LongLanguageStr("Hebrew"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ja"),
        LongLanguageStr("Japanese"),
    ),
    (
        "jw",
        LongLanguageStr("Javanese"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ka"),
        LongLanguageStr("Georgian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("kk"),
        LongLanguageStr("Kazakh"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("km"),
        LongLanguageStr("Central Khmer"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("kn"),
        LongLanguageStr("Kannada"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ko"),
        LongLanguageStr("Korean"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("la"),
        LongLanguageStr("Latin"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("lb"),
        LongLanguageStr("Luxembourgish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ln"),
        LongLanguageStr("Lingala"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("lo"),
        LongLanguageStr("Lao"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("lt"),
        LongLanguageStr("Lithuanian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("lv"),
        LongLanguageStr("Latvian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("mg"),
        LongLanguageStr("Malagasy"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("mi"),
        LongLanguageStr("Maori"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("mk"),
        LongLanguageStr("Macedonian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ml"),
        LongLanguageStr("Malayalam"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("mn"),
        LongLanguageStr("Mongolian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("mr"),
        LongLanguageStr("Marathi"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ms"),
        LongLanguageStr("Malay"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("mt"),
        LongLanguageStr("Maltese"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("my"),
        LongLanguageStr("Burmese"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ne"),
        LongLanguageStr("Nepali"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("nl"),
        LongLanguageStr("Dutch"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("nn"),
        LongLanguageStr("Norwegian Nynorsk"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("no"),
        LongLanguageStr("Norwegian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("oc"),
        LongLanguageStr("Occitan"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("pa"),
        LongLanguageStr("Panjabi"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("pl"),
        LongLanguageStr("Polish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ps"),
        LongLanguageStr("Pushto"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("pt"),
        LongLanguageStr("Portuguese"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ro"),
        LongLanguageStr("Romanian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ru"),
        LongLanguageStr("Russian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sa"),
        LongLanguageStr("Sanskrit"),
    ),
    (
        Alpha3LanguageStr.from_str_unsafe("sco"),
        LongLanguageStr("Scots"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sd"),
        LongLanguageStr("Sindhi"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("si"),
        LongLanguageStr("Sinhala"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sk"),
        LongLanguageStr("Slovak"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sl"),
        LongLanguageStr("Slovenian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sn"),
        LongLanguageStr("Shona"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("so"),
        LongLanguageStr("Somali"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sq"),
        LongLanguageStr("Albanian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sr"),
        LongLanguageStr("Serbian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("su"),
        LongLanguageStr("Sundanese"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sv"),
        LongLanguageStr("Swedish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("sw"),
        LongLanguageStr("Swahili"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ta"),
        LongLanguageStr("Tamil"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("te"),
        LongLanguageStr("Telugu"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("tg"),
        LongLanguageStr("Tajik"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("th"),
        LongLanguageStr("Thai"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("tk"),
        LongLanguageStr("Turkmen"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("tl"),
        LongLanguageStr("Tagalog"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("tr"),
        LongLanguageStr("Turkish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("tt"),
        LongLanguageStr("Tatar"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("uk"),
        LongLanguageStr("Ukrainian"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("ur"),
        LongLanguageStr("Urdu"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("uz"),
        LongLanguageStr("Uzbek"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("vi"),
        LongLanguageStr("Vietnamese"),
    ),
    (
        Alpha3LanguageStr.from_str_unsafe("war"),
        LongLanguageStr("Waray"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("yi"),
        LongLanguageStr("Yiddish"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("yo"),
        LongLanguageStr("Yoruba"),
    ),
    (
        Alpha2LanguageStr.from_str_unsafe("zh"),
        LongLanguageStr("Mandarin Chinese"),
    ),
]


class ModelLanguageHelper:
    pass


voxlingua107_ecapa_language_helper = ModelLanguageHelper()

voxlingua107_ecapa_model: Model = Model(
    name="voxlingua107",
    sample_count=voxlingua107_ecapa_languages_count,
    source="speechbrain/lang-id-voxlingua107-ecapa",
    bitrate=16000,
    memory_pattern=MemoryPatternLinear(
        coeffs=LinearCoeffs(c=121287679.99999952, m=12845499.313230773),
    ),
    # language_helper=voxlingua107_ecapa_language_helper,
)


lang_model_2 = [
    "Arabic",
    "Basque",
    "Breton",
    "Catalan",
    "Chinese_China",
    "Chinese_Hongkong",
    "Chinese_Taiwan",
    "Chuvash",
    "Czech",
    "Dhivehi",
    "Dutch",
    "English",
    "Esperanto",
    "Estonian",
    "French",
    "Frisian",
    "Georgian",
    "German",
    "Greek",
    "Hakha_Chin",
    "Indonesian",
    "Interlingua",
    "Italian",
    "Japanese",
    "Kabyle",
    "Kinyarwanda",
    "Kyrgyz",
    "Latvian",
    "Maltese",
    "Mongolian",
    "Persian",
    "Polish",
    "Portuguese",
    "Romanian",
    "Romansh_Sursilvan",
    "Russian",
    "Sakha",
    "Slovenian",
    "Spanish",
    "Swedish",
    "Tamil",
    "Tatar",
    "Turkish",
    "Ukrainian",
    "Welsh",
]
