from typing import Optional

Iso_3Alpha = str
Iso_3AlphaTwoPossibilities = tuple[str, str]
Iso_2Alpha = str
EngName = str


IsoLanguage = tuple[
    Iso_3Alpha | Iso_3AlphaTwoPossibilities,
    Optional[Iso_2Alpha],
    EngName | list[EngName],
    str,
    str,
]

# generated from: https://www.loc.gov/standards/iso639-2/php/code_list.php
# with the js: Array.from(document.querySelectorAll("table")[1].querySelectorAll("tr")).map(tr=>Array.from(tr.querySelectorAll("td")).map(a=>a.textContent.trim()))


valid_iso_639_2_languages_list: list[IsoLanguage] = [
    ("aar", "aa", "Afar", "afar", "Danakil-Sprache"),
    ("abk", "ab", "Abkhazian", "abkhaze", "Abchasisch"),
    ("ace", None, "Achinese", "aceh", "Aceh-Sprache"),
    ("ach", None, "Acoli", "acoli", "Acholi-Sprache"),
    ("ada", None, "Adangme", "adangme", "Adangme-Sprache"),
    ("ady", None, "Adyghe; Adygei", "adyghé", "Adygisch"),
    (
        "afa",
        None,
        "Afro-Asiatic languages",
        "afro-asiatiques, langues",
        "Hamitosemitische Sprachen (Andere)",
    ),
    ("afh", None, "Afrihili", "afrihili", "Afrihili"),
    ("afr", "af", "Afrikaans", "afrikaans", "Afrikaans"),
    ("ain", None, "Ainu", "aïnou", "Ainu-Sprache"),
    ("aka", "ak", "Akan", "akan", "Akan-Sprache"),
    ("akk", None, "Akkadian", "akkadien", "Akkadisch"),
    (("alb", "sqi"), "sq", "Albanian", "albanais", "Albanisch"),
    ("ale", None, "Aleut", "aléoute", "Aleutisch"),
    (
        "alg",
        None,
        "Algonquian languages",
        "algonquines, langues",
        "Algonkin-Sprachen (Andere)",
    ),
    ("alt", None, "Southern Altai", "altai du Sud", "Altaisch"),
    ("amh", "am", "Amharic", "amharique", "Amharisch"),
    (
        "ang",
        None,
        "English, Old (ca.450-1100)",
        "anglo-saxon (ca.450-1100)",
        "Altenglisch",
    ),
    ("anp", None, "Angika", "angika", "Anga-Sprache"),
    ("apa", None, "Apache languages", "apaches, langues", "Apachen-Sprachen"),
    ("ara", "ar", "Arabic", "arabe", "Arabisch"),
    (
        "arc",
        None,
        "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)",
        "araméen d'empire (700-300 BCE)",
        "Aramäisch",
    ),
    ("arg", "an", "Aragonese", "aragonais", "Aragonesisch"),
    (("arm", "hye"), "hy", "Armenian", "arménien", "Armenisch"),
    (
        "arn",
        None,
        "Mapudungun; Mapuche",
        "mapudungun; mapuche; mapuce",
        "Arauka-Sprachen",
    ),
    ("arp", None, "Arapaho", "arapaho", "Arapaho-Sprache"),
    (
        "art",
        None,
        "Artificial languages",
        "artificielles, langues",
        "Kunstsprachen (Andere)",
    ),
    ("arw", None, "Arawak", "arawak", "Arawak-Sprachen"),
    ("asm", "as", "Assamese", "assamais", "Assamesisch"),
    (
        "ast",
        None,
        "Asturian; Bable; Leonese; Asturleonese",
        "asturien; bable; léonais; asturoléonais",
        "Asturisch",
    ),
    (
        "ath",
        None,
        "Athapascan languages",
        "athapascanes, langues",
        "Athapaskische Sprachen (Andere)",
    ),
    (
        "aus",
        None,
        "Australian languages",
        "australiennes, langues",
        "Australische Sprachen",
    ),
    ("ava", "av", "Avaric", "avar", "Awarisch"),
    ("ave", "ae", "Avestan", "avestique", "Avestisch"),
    ("awa", None, "Awadhi", "awadhi", "Awadhi"),
    ("aym", "ay", "Aymara", "aymara", "Aymará-Sprache"),
    ("aze", "az", "Azerbaijani", "azéri", "Aserbeidschanisch"),
    (
        "bad",
        None,
        "Banda languages",
        "banda, langues",
        "Banda-Sprachen (Ubangi-Sprachen)",
    ),
    ("bai", None, "Bamileke languages", "bamiléké, langues", "Bamileke-Sprachen"),
    ("bak", "ba", "Bashkir", "bachkir", "Baschkirisch"),
    ("bal", None, "Baluchi", "baloutchi", "Belutschisch"),
    ("bam", "bm", "Bambara", "bambara", "Bambara-Sprache"),
    ("ban", None, "Balinese", "balinais", "Balinesisch"),
    (("baq", "eus"), "eu", "Basque", "basque", "Baskisch"),
    ("bas", None, "Basa", "basa", "Basaa-Sprache"),
    ("bat", None, "Baltic languages", "baltes, langues", "Baltische Sprachen (Andere)"),
    ("bej", None, "Beja; Bedawiyet", "bedja", "Bedauye"),
    ("bel", "be", "Belarusian", "biélorusse", "Weißrussisch"),
    ("bem", None, "Bemba", "bemba", "Bemba-Sprache"),
    ("ben", "bn", "Bengali", "bengali", "Bengali"),
    ("ber", None, "Berber languages", "berbères, langues", "Berbersprachen (Andere)"),
    ("bho", None, "Bhojpuri", "bhojpuri", "Bhojpuri"),
    ("bih", None, "Bihari languages", "langues biharis", "Bihari (Andere)"),
    ("bik", None, "Bikol", "bikol", "Bikol-Sprache"),
    ("bin", None, "Bini; Edo", "bini; edo", "Edo-Sprache"),
    ("bis", "bi", "Bislama", "bichlamar", "Beach-la-mar"),
    ("bla", None, "Siksika", "blackfoot", "Blackfoot-Sprache"),
    ("bnt", None, "Bantu languages", "bantou, langues", "Bantusprachen (Andere)"),
    (("tib", "bod"), "bo", "Tibetan", "tibétain", "Tibetisch"),
    ("bos", "bs", "Bosnian", "bosniaque", "Bosnisch"),
    ("bra", None, "Braj", "braj", "Braj-Bhakha"),
    ("bre", "br", "Breton", "breton", "Bretonisch"),
    ("btk", None, "Batak languages", "batak, langues", "Batak-Sprache"),
    ("bua", None, "Buriat", "bouriate", "Burjatisch"),
    ("bug", None, "Buginese", "bugi", "Bugi-Sprache"),
    ("bul", "bg", "Bulgarian", "bulgare", "Bulgarisch"),
    (("bur", "mya"), "my", "Burmese", "birman", "Birmanisch"),
    ("byn", None, "Blin; Bilin", "blin; bilen", "Bilin-Sprache"),
    ("cad", None, "Caddo", "caddo", "Caddo-Sprachen"),
    (
        "cai",
        None,
        "Central American Indian languages",
        "amérindiennes de l'Amérique centrale,  langues",
        "Indianersprachen, Zentralamerika (Andere)",
    ),
    ("car", None, "Galibi Carib", "karib; galibi; carib", "Karibische Sprachen"),
    ("cat", "ca", "Catalan; Valencian", "catalan; valencien", "Katalanisch"),
    (
        "cau",
        None,
        "Caucasian languages",
        "caucasiennes, langues",
        "Kaukasische Sprachen (Andere)",
    ),
    ("ceb", None, "Cebuano", "cebuano", "Cebuano"),
    (
        "cel",
        None,
        "Celtic languages",
        "celtiques, langues; celtes, langues",
        "Keltische Sprachen (Andere)",
    ),
    (("cze", "ces"), "cs", "Czech", "tchèque", "Tschechisch"),
    ("cha", "ch", "Chamorro", "chamorro", "Chamorro-Sprache"),
    ("chb", None, "Chibcha", "chibcha", "Chibcha-Sprachen"),
    ("che", "ce", "Chechen", "tchétchène", "Tschetschenisch"),
    ("chg", None, "Chagatai", "djaghataï", "Tschagataisch"),
    (("chi", "zho"), "zh", "Chinese", "chinois", "Chinesisch"),
    ("chk", None, "Chuukese", "chuuk", "Trukesisch"),
    ("chm", None, "Mari", "mari", "Tscheremissisch"),
    ("chn", None, "Chinook jargon", "chinook, jargon", "Chinook-Jargon"),
    ("cho", None, "Choctaw", "choctaw", "Choctaw-Sprache"),
    ("chp", None, "Chipewyan; Dene Suline", "chipewyan", "Chipewyan-Sprache"),
    ("chr", None, "Cherokee", "cherokee", "Cherokee-Sprache"),
    (
        "chu",
        "cu",
        "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
        "slavon d'église; vieux slave; slavon liturgique; vieux bulgare",
        "Kirchenslawisch",
    ),
    ("chv", "cv", "Chuvash", "tchouvache", "Tschuwaschisch"),
    ("chy", None, "Cheyenne", "cheyenne", "Cheyenne-Sprache"),
    ("cmc", None, "Chamic languages", "chames, langues", "Cham-Sprachen"),
    ("cnr", None, "Montenegrin", "monténégrin", "Montenegrinisch"),
    ("cop", None, "Coptic", "copte", "Koptisch"),
    ("cor", "kw", "Cornish", "cornique", "Kornisch"),
    ("cos", "co", "Corsican", "corse", "Korsisch"),
    (
        "cpe",
        None,
        "Creoles and pidgins, English based",
        "créoles et pidgins basés sur l'anglais",
        "Kreolisch-Englisch (Andere)",
    ),
    (
        "cpf",
        None,
        "Creoles and pidgins, French-based",
        "créoles et pidgins basés sur le français",
        "Kreolisch-Französisch (Andere)",
    ),
    (
        "cpp",
        None,
        "Creoles and pidgins, Portuguese-based",
        "créoles et pidgins basés sur le portugais",
        "Kreolisch-Portugiesisch (Andere)",
    ),
    ("cre", "cr", "Cree", "cree", "Cree-Sprache"),
    ("crh", None, "Crimean Tatar; Crimean Turkish", "tatar de Crimé", "Krimtatarisch"),
    (
        "crp",
        None,
        "Creoles and pidgins",
        "créoles et pidgins",
        "Kreolische Sprachen; Pidginsprachen (Andere)",
    ),
    ("csb", None, "Kashubian", "kachoube", "Kaschubisch"),
    (
        "cus",
        None,
        "Cushitic languages",
        "couchitiques,  langues",
        "Kuschitische Sprachen (Andere)",
    ),
    (("wel", "cym"), "cy", "Welsh", "gallois", "Kymrisch"),
    (("cze", "ces"), "cs", "Czech", "tchèque", "Tschechisch"),
    ("dak", None, "Dakota", "dakota", "Dakota-Sprache"),
    ("dan", "da", "Danish", "danois", "Dänisch"),
    ("dar", None, "Dargwa", "dargwa", "Darginisch"),
    ("day", None, "Land Dayak languages", "dayak, langues", "Dajakisch"),
    ("del", None, "Delaware", "delaware", "Delaware-Sprache"),
    ("den", None, "Slave (Athapascan)", "esclave (athapascan)", "Slave-Sprache"),
    (("ger", "deu"), "de", "German", "allemand", "Deutsch"),
    ("dgr", None, "Tlicho; Dogrib", "tlicho; dogrib", "Tlicho-Sprache; Dogrib-Sprache"),
    ("din", None, "Dinka", "dinka", "Dinka-Sprache"),
    ("div", "dv", "Divehi; Dhivehi; Maldivian", "maldivien", "Maledivisch"),
    ("doi", None, "Dogri (macrolanguage)", "dogri", "Dogri"),
    (
        "dra",
        None,
        "Dravidian languages",
        "dravidiennes,  langues",
        "Drawidische Sprachen (Andere)",
    ),
    ("dsb", None, "Lower Sorbian", "bas-sorabe", "Niedersorbisch"),
    ("dua", None, "Duala", "douala", "Duala-Sprachen"),
    (
        "dum",
        None,
        "Dutch, Middle (ca.1050-1350)",
        "néerlandais moyen (ca. 1050-1350)",
        "Mittelniederländisch",
    ),
    (
        ("dut", "nld"),
        "nl",
        "Dutch; Flemish",
        "néerlandais; flamand",
        "Niederländisch",
    ),
    ("dyu", None, "Dyula", "dioula", "Dyula-Sprache"),
    ("dzo", "dz", "Dzongkha", "dzongkha", "Dzongkha"),
    ("efi", None, "Efik", "efik", "Efik"),
    ("egy", None, "Egyptian (Ancient)", "égyptien", "Ägyptisch"),
    ("eka", None, "Ekajuk", "ekajuk", "Ekajuk"),
    (
        ("gre", "ell"),
        "el",
        "Modern Greek (1453-)",
        "grec moderne (1453-)",
        "Neugriechisch",
    ),
    ("elx", None, "Elamite", "élamite", "Elamisch"),
    ("eng", "en", "English", "anglais", "Englisch"),
    (
        "enm",
        None,
        "English, Middle (1100-1500)",
        "anglais moyen (1100-1500)",
        "Mittelenglisch",
    ),
    ("epo", "eo", "Esperanto", "espéranto", "Esperanto"),
    ("est", "et", "Estonian", "estonien", "Estnisch"),
    (("baq", "eus"), "eu", "Basque", "basque", "Baskisch"),
    ("ewe", "ee", "Ewe", "éwé", "Ewe-Sprache"),
    ("ewo", None, "Ewondo", "éwondo", "Ewondo"),
    ("fan", None, "Fang", "fang", "Pangwe-Sprache"),
    ("fao", "fo", "Faroese", "féroïen", "Färöisch"),
    (("per", "fas"), "fa", "Persian", "persan", "Persisch"),
    ("fat", None, "Fanti", "fanti", "Fante-Sprache"),
    ("fij", "fj", "Fijian", "fidjien", "Fidschi-Sprache"),
    ("fil", None, "Filipino; Pilipino", "filipino; pilipino", "Pilipino"),
    ("fin", "fi", "Finnish", "finnois", "Finnisch"),
    (
        "fiu",
        None,
        "Finno-Ugrian languages",
        "finno-ougriennes,  langues",
        "Finnougrische Sprachen (Andere)",
    ),
    ("fon", None, "Fon", "fon", "Fon-Sprache"),
    (("fre", "fra"), "fr", "French", "français", "Französisch"),
    (("fre", "fra"), "fr", "French", "français", "Französisch"),
    (
        "frm",
        None,
        "French, Middle (ca.1400-1600)",
        "français moyen (1400-1600)",
        "Mittelfranzösisch",
    ),
    (
        "fro",
        None,
        "French, Old (842-ca.1400)",
        "français ancien (842-ca.1400)",
        "Altfranzösisch",
    ),
    ("frr", None, "Northern Frisian", "frison septentrional", "Nordfriesisch"),
    ("frs", None, "Eastern Frisian", "frison oriental", "Ostfriesisch"),
    ("fry", "fy", "Western Frisian", "frison occidental", "Friesisch"),
    ("ful", "ff", "Fulah", "peul", "Ful"),
    ("fur", None, "Friulian", "frioulan", "Friulisch"),
    ("gaa", None, "Ga", "ga", "Ga-Sprache"),
    ("gay", None, "Gayo", "gayo", "Gayo-Sprache"),
    ("gba", None, "Gbaya", "gbaya", "Gbaya-Sprache"),
    (
        "gem",
        None,
        "Germanic languages",
        "germaniques, langues",
        "Germanische Sprachen (Andere)",
    ),
    (("geo", "kat"), "ka", "Georgian", "géorgien", "Georgisch"),
    (("ger", "deu"), "de", "German", "allemand", "Deutsch"),
    ("gez", None, "Geez", "guèze", "Altäthiopisch"),
    ("gil", None, "Gilbertese", "kiribati", "Gilbertesisch"),
    (
        "gla",
        "gd",
        "Gaelic; Scottish Gaelic",
        "gaélique; gaélique écossais",
        "Gälisch-Schottisch",
    ),
    ("gle", "ga", "Irish", "irlandais", "Irisch"),
    ("glg", "gl", "Galician", "galicien", "Galicisch"),
    ("glv", "gv", "Manx", "manx; mannois", "Manx"),
    (
        "gmh",
        None,
        "German, Middle High (ca.1050-1500)",
        "allemand, moyen haut (ca. 1050-1500)",
        "Mittelhochdeutsch",
    ),
    (
        "goh",
        None,
        "German, Old High (ca.750-1050)",
        "allemand, vieux haut (ca. 750-1050)",
        "Althochdeutsch",
    ),
    ("gon", None, "Gondi", "gond", "Gondi-Sprache"),
    ("gor", None, "Gorontalo", "gorontalo", "Gorontalesisch"),
    ("got", None, "Gothic", "gothique", "Gotisch"),
    ("grb", None, "Grebo", "grebo", "Grebo-Sprache"),
    (
        "grc",
        None,
        "Greek, Ancient (to 1453)",
        "grec ancien (jusqu'à 1453)",
        "Griechisch",
    ),
    (
        ("gre", "ell"),
        "el",
        "Modern Greek (1453-)",
        "grec moderne (1453-)",
        "Neugriechisch",
    ),
    ("grn", "gn", "Guarani", "guarani", "Guaraní-Sprache"),
    (
        "gsw",
        None,
        "Swiss German; Alemannic; Alsatian",
        "suisse alémanique; alémanique; alsacien",
        "Schweizerdeutsch",
    ),
    ("guj", "gu", "Gujarati", "goudjrati", "Gujarati-Sprache"),
    ("gwi", None, "Gwich'in", "gwich'in", "Kutchin-Sprache"),
    ("hai", None, "Haida", "haida", "Haida-Sprache"),
    (
        "hat",
        "ht",
        "Haitian; Haitian Creole",
        "haïtien; créole haïtien",
        "Haïtien (Haiti-Kreolisch)",
    ),
    ("hau", "ha", "Hausa", "haoussa", "Haussa-Sprache"),
    ("haw", None, "Hawaiian", "hawaïen", "Hawaiisch"),
    ("heb", "he", "Hebrew", "hébreu", "Hebräisch"),
    ("her", "hz", "Herero", "herero", "Herero-Sprache"),
    ("hil", None, "Hiligaynon", "hiligaynon", "Hiligaynon-Sprache"),
    (
        "him",
        None,
        "Himachali languages; Western Pahari languages",
        "langues himachalis; langues paharis occidentales",
        "Himachali",
    ),
    ("hin", "hi", "Hindi", "hindi", "Hindi"),
    ("hit", None, "Hittite", "hittite", "Hethitisch"),
    ("hmn", None, "Hmong; Mong", "hmong", "Miao-Sprachen"),
    ("hmo", "ho", "Hiri Motu", "hiri motu", "Hiri-Motu"),
    ("hrv", "hr", "Croatian", "croate", "Kroatisch"),
    ("hsb", None, "Upper Sorbian", "haut-sorabe", "Obersorbisch"),
    ("hun", "hu", "Hungarian", "hongrois", "Ungarisch"),
    ("hup", None, "Hupa", "hupa", "Hupa-Sprache"),
    (("arm", "hye"), "hy", "Armenian", "arménien", "Armenisch"),
    ("iba", None, "Iban", "iban", "Iban-Sprache"),
    ("ibo", "ig", "Igbo", "igbo", "Ibo-Sprache"),
    (("ice", "isl"), "is", "Icelandic", "islandais", "Isländisch"),
    ("ido", "io", "Ido", "ido", "Ido"),
    ("iii", "ii", "Sichuan Yi; Nuosu", "yi de Sichuan", "Lalo-Sprache"),
    ("ijo", None, "Ijo languages", "ijo, langues", "Ijo-Sprache"),
    ("iku", "iu", "Inuktitut", "inuktitut", "Inuktitut"),
    ("ile", "ie", "Interlingue; Occidental", "interlingue", "Interlingue"),
    ("ilo", None, "Iloko", "ilocano", "Ilokano-Sprache"),
    (
        "ina",
        "ia",
        "Interlingua (International Auxiliary Language Association)",
        "interlingua (langue auxiliaire internationale)",
        "Interlingua",
    ),
    (
        "inc",
        None,
        "Indic languages",
        "indo-aryennes, langues",
        "Indoarische Sprachen (Andere)",
    ),
    ("ind", "id", "Indonesian", "indonésien", "Bahasa Indonesia"),
    (
        "ine",
        None,
        "Indo-European languages",
        "indo-européennes, langues",
        "Indogermanische Sprachen (Andere)",
    ),
    ("inh", None, "Ingush", "ingouche", "Inguschisch"),
    ("ipk", "ik", "Inupiaq", "inupiaq", "Inupik"),
    (
        "ira",
        None,
        "Iranian languages",
        "iraniennes, langues",
        "Iranische Sprachen (Andere)",
    ),
    ("iro", None, "Iroquoian languages", "iroquoises, langues", "Irokesische Sprachen"),
    (("ice", "isl"), "is", "Icelandic", "islandais", "Isländisch"),
    ("ita", "it", "Italian", "italien", "Italienisch"),
    ("jav", "jv", "Javanese", "javanais", "Javanisch"),
    ("jbo", None, "Lojban", "lojban", "Lojban"),
    ("jpn", "ja", "Japanese", "japonais", "Japanisch"),
    ("jpr", None, "Judeo-Persian", "judéo-persan", "Jüdisch-Persisch"),
    ("jrb", None, "Judeo-Arabic", "judéo-arabe", "Jüdisch-Arabisch"),
    ("kaa", None, "Kara-Kalpak", "karakalpak", "Karakalpakisch"),
    ("kab", None, "Kabyle", "kabyle", "Kabylisch"),
    ("kac", None, "Kachin; Jingpho", "kachin; jingpho", "Kachin-Sprache"),
    ("kal", "kl", "Kalaallisut; Greenlandic", "groenlandais", "Grönländisch"),
    ("kam", None, "Kamba", "kamba", "Kamba-Sprache"),
    ("kan", "kn", "Kannada", "kannada", "Kannada"),
    ("kar", None, "Karen languages", "karen, langues", "Karenisch"),
    ("kas", "ks", "Kashmiri", "kashmiri", "Kaschmiri"),
    (("geo", "kat"), "ka", "Georgian", "géorgien", "Georgisch"),
    ("kau", "kr", "Kanuri", "kanouri", "Kanuri-Sprache"),
    ("kaw", None, "Kawi", "kawi", "Kawi"),
    ("kaz", "kk", "Kazakh", "kazakh", "Kasachisch"),
    ("kbd", None, "Kabardian", "kabardien", "Kabardinisch"),
    ("kha", None, "Khasi", "khasi", "Khasi-Sprache"),
    ("khi", None, "Khoisan languages", "khoïsan, langues", "Khoisan-Sprachen (Andere)"),
    ("khm", "km", "Central Khmer", "khmer central", "Kambodschanisch"),
    ("kho", None, "Khotanese; Sakan", "khotanais; sakan", "Sakisch"),
    ("kik", "ki", "Kikuyu; Gikuyu", "kikuyu", "Kikuyu-Sprache"),
    ("kin", "rw", "Kinyarwanda", "rwanda", "Rwanda-Sprache"),
    ("kir", "ky", "Kirghiz; Kyrgyz", "kirghiz", "Kirgisisch"),
    ("kmb", None, "Kimbundu", "kimbundu", "Kimbundu-Sprache"),
    ("kok", None, "Konkani (macrolanguage)", "konkani", "Konkani"),
    ("kom", "kv", "Komi", "kom", "Komi-Sprache"),
    ("kon", "kg", "Kongo", "kongo", "Kongo-Sprache"),
    ("kor", "ko", "Korean", "coréen", "Koreanisch"),
    ("kos", None, "Kosraean", "kosrae", "Kosraeanisch"),
    ("kpe", None, "Kpelle", "kpellé", "Kpelle-Sprache"),
    ("krc", None, "Karachay-Balkar", "karatchai balkar", "Karatschaiisch-Balkarisch"),
    ("krl", None, "Karelian", "carélien", "Karelisch"),
    ("kro", None, "Kru languages", "krou, langues", "Kru-Sprachen (Andere)"),
    ("kru", None, "Kurukh", "kurukh", "Oraon-Sprache"),
    ("kua", "kj", "Kuanyama; Kwanyama", "kuanyama; kwanyama", "Kwanyama-Sprache"),
    ("kum", None, "Kumyk", "koumyk", "Kumükisch"),
    ("kur", "ku", "Kurdish", "kurde", "Kurdisch"),
    ("kut", None, "Kutenai", "kutenai", "Kutenai-Sprache"),
    ("lad", None, "Ladino", "judéo-espagnol", "Judenspanisch"),
    ("lah", None, "Lahnda", "lahnda", "Lahnda"),
    ("lam", None, "Lamba", "lamba", "Lamba-Sprache (Bantusprache)"),
    ("lao", "lo", "Lao", "lao", "Laotisch"),
    ("lat", "la", "Latin", "latin", "Latein"),
    ("lav", "lv", "Latvian", "letton", "Lettisch"),
    ("lez", None, "Lezghian", "lezghien", "Lesgisch"),
    ("lim", "li", "Limburgan; Limburger; Limburgish", "limbourgeois", "Limburgisch"),
    ("lin", "ln", "Lingala", "lingala", "Lingala"),
    ("lit", "lt", "Lithuanian", "lituanien", "Litauisch"),
    ("lol", None, "Mongo", "mongo", "Mongo-Sprache"),
    ("loz", None, "Lozi", "lozi", "Rotse-Sprache"),
    ("ltz", "lb", "Luxembourgish; Letzeburgesch", "luxembourgeois", "Luxemburgisch"),
    ("lua", None, "Luba-Lulua", "luba-lulua", "Lulua-Sprache"),
    ("lub", "lu", "Luba-Katanga", "luba-katanga", "Luba-Katanga-Sprache"),
    ("lug", "lg", "Ganda", "ganda", "Ganda-Sprache"),
    ("lui", None, "Luiseño", "luiseño", "Luiseño-Sprache"),
    ("lun", None, "Lunda", "lunda", "Lunda-Sprache"),
    ("luo", None, "Luo (Kenya and Tanzania)", "luo (Kenya et Tanzanie)", "Luo-Sprache"),
    ("lus", None, "Lushai", "lushai", "Lushai-Sprache"),
    (("mac", "mkd"), "mk", "Macedonian", "macédonien", "Makedonisch"),
    ("mad", None, "Madurese", "madourais", "Maduresisch"),
    ("mag", None, "Magahi", "magahi", "Khotta"),
    ("mah", "mh", "Marshallese", "marshall", "Marschallesisch"),
    ("mai", None, "Maithili", "maithili", "Maithili"),
    ("mak", None, "Makasar", "makassar", "Makassarisch"),
    ("mal", "ml", "Malayalam", "malayalam", "Malayalam"),
    ("man", None, "Mandingo", "mandingue", "Malinke-Sprache"),
    (("mao", "mri"), "mi", "Maori", "maori", "Maori-Sprache"),
    (
        "map",
        None,
        "Austronesian languages",
        "austronésiennes, langues",
        "Austronesische Sprachen (Andere)",
    ),
    ("mar", "mr", "Marathi", "marathe", "Marathi"),
    ("mas", None, "Masai", "massaï", "Massai-Sprache"),
    (("may", "msa"), "ms", "Malay (macrolanguage)", "malais", "Malaiisch"),
    ("mdf", None, "Moksha", "moksa", "Mokscha-Sprache"),
    ("mdr", None, "Mandar", "mandar", "Mandaresisch"),
    ("men", None, "Mende", "mendé", "Mende-Sprache"),
    (
        "mga",
        None,
        "Irish, Middle (900-1200)",
        "irlandais moyen (900-1200)",
        "Mittelirisch",
    ),
    ("mic", None, "Mi'kmaq; Micmac", "mi'kmaq; micmac", "Micmac-Sprache"),
    ("min", None, "Minangkabau", "minangkabau", "Minangkabau-Sprache"),
    (
        "mis",
        None,
        "Uncoded languages",
        "langues non codées",
        "Einzelne andere Sprachen",
    ),
    (("mac", "mkd"), "mk", "Macedonian", "macédonien", "Makedonisch"),
    (
        "mkh",
        None,
        "Mon-Khmer languages",
        "môn-khmer, langues",
        "Mon-Khmer-Sprachen (Andere)",
    ),
    ("mlg", "mg", "Malagasy", "malgache", "Malagassi-Sprache"),
    ("mlt", "mt", "Maltese", "maltais", "Maltesisch"),
    ("mnc", None, "Manchu", "mandchou", "Mandschurisch"),
    ("mni", None, "Manipuri", "manipuri", "Meithei-Sprache"),
    ("mno", None, "Manobo languages", "manobo, langues", "Manobo-Sprachen"),
    ("moh", None, "Mohawk", "mohawk", "Mohawk-Sprache"),
    ("mon", "mn", "Mongolian", "mongol", "Mongolisch"),
    ("mos", None, "Mossi", "moré", "Mossi-Sprache"),
    (("mao", "mri"), "mi", "Maori", "maori", "Maori-Sprache"),
    (("may", "msa"), "ms", "Malay (macrolanguage)", "malais", "Malaiisch"),
    ("mul", None, "Multiple languages", "multilingue", "Mehrere Sprachen"),
    ("mun", None, "Munda languages", "mounda, langues", "Mundasprachen (Andere)"),
    ("mus", None, "Creek", "muskogee", "Muskogisch"),
    ("mwl", None, "Mirandese", "mirandais", "Mirandesisch"),
    ("mwr", None, "Marwari", "marvari", "Marwari"),
    (("bur", "mya"), "my", "Burmese", "birman", "Birmanisch"),
    ("myn", None, "Mayan languages", "maya, langues", "Maya-Sprachen"),
    ("myv", None, "Erzya", "erza", "Erza-Mordwinisch"),
    ("nah", None, "Nahuatl languages", "nahuatl, langues", "Nahuatl"),
    (
        "nai",
        None,
        "North American Indian languages",
        "nord-amérindiennes, langues",
        "Indianersprachen, Nordamerika (Andere)",
    ),
    ("nap", None, "Neapolitan", "napolitain", "Neapel / Mundart"),
    ("nau", "na", "Nauru", "nauruan", "Nauruanisch"),
    ("nav", "nv", "Navajo; Navaho", "navaho", "Navajo-Sprache"),
    ("nbl", "nr", "South Ndebele", "ndébélé du Sud", "Ndebele-Sprache (Transvaal)"),
    ("nde", "nd", "North Ndebele", "ndébélé du Nord", "Ndebele-Sprache (Simbabwe)"),
    ("ndo", "ng", "Ndonga", "ndonga", "Ndonga"),
    (
        "nds",
        None,
        "Low German; Low Saxon; German, Low; Saxon, Low",
        "bas allemand; bas saxon; allemand, bas; saxon, bas",
        "Niederdeutsch",
    ),
    ("nep", "ne", "Nepali (macrolanguage)", "népalais", "Nepali"),
    ("new", None, "Nepal Bhasa; Newar; Newari", "nepal bhasa; néwar; newari", "Newari"),
    ("nia", None, "Nias", "nias", "Nias-Sprache"),
    (
        "nic",
        None,
        "Niger-Kordofanian languages",
        "nigéro-kordofaniennes, langues",
        "Nigerkordofanische Sprachen (Andere)",
    ),
    ("niu", None, "Niuean", "niué", "Niue-Sprache"),
    (
        ("dut", "nld"),
        "nl",
        "Dutch; Flemish",
        "néerlandais; flamand",
        "Niederländisch",
    ),
    ("nno", "nn", "Norwegian Nynorsk", "norvégien nynorsk", "Nynorsk"),
    ("nob", "nb", "Norwegian Bokmål", "norvégien bokmål", "Bokmål"),
    ("nog", None, "Nogai", "nogaï; nogay", "Nogaisch"),
    ("non", None, "Norse, Old", "norrois, vieux", "Altnorwegisch"),
    ("nor", "no", "Norwegian", "norvégien", "Norwegisch"),
    ("nqo", None, "N'Ko", "n'ko", "N'Ko"),
    (
        "nso",
        None,
        "Pedi; Sepedi; Northern Sotho",
        "pedi; sepedi; sotho du Nord",
        "Pedi-Sprache",
    ),
    ("nub", None, "Nubian languages", "nubiennes, langues", "Nubische Sprachen"),
    (
        "nwc",
        None,
        "Classical Newari; Old Newari; Classical Nepal Bhasa",
        "newari classique",
        "Alt-Newari",
    ),
    (
        "nya",
        "ny",
        "Chichewa; Chewa; Nyanja",
        "chichewa; chewa; nyanja",
        "Nyanja-Sprache",
    ),
    ("nym", None, "Nyamwezi", "nyamwezi", "Nyamwezi-Sprache"),
    ("nyn", None, "Nyankole", "nyankolé", "Nkole-Sprache"),
    ("nyo", None, "Nyoro", "nyoro", "Nyoro-Sprache"),
    ("nzi", None, "Nzima", "nzema", "Nzima-Sprache"),
    ("oci", "oc", "Occitan (post 1500)", "occitan (après 1500)", "Okzitanisch"),
    ("oji", "oj", "Ojibwa", "ojibwa", "Ojibwa-Sprache"),
    ("ori", "or", "Oriya (macrolanguage)", "oriya", "Oriya-Sprache"),
    ("orm", "om", "Oromo", "galla", "Galla-Sprache"),
    ("osa", None, "Osage", "osage", "Osage-Sprache"),
    ("oss", "os", "Ossetian; Ossetic", "ossète", "Ossetisch"),
    (
        "ota",
        None,
        "Turkish, Ottoman (1500-1928)",
        "turc ottoman (1500-1928)",
        "Osmanisch",
    ),
    ("oto", None, "Otomian languages", "otomi, langues", "Otomangue-Sprachen"),
    ("paa", None, "Papuan languages", "papoues, langues", "Papuasprachen (Andere)"),
    ("pag", None, "Pangasinan", "pangasinan", "Pangasinan-Sprache"),
    ("pal", None, "Pahlavi", "pahlavi", "Mittelpersisch"),
    ("pam", None, "Pampanga; Kapampangan", "pampangan", "Pampanggan-Sprache"),
    ("pan", "pa", "Panjabi; Punjabi", "pendjabi", "Pandschabi-Sprache"),
    ("pap", None, "Papiamento", "papiamento", "Papiamento"),
    ("pau", None, "Palauan", "palau", "Palau-Sprache"),
    (
        "peo",
        None,
        "Persian, Old (ca.600-400 B.C.)",
        "perse, vieux (ca. 600-400 av. J.-C.)",
        "Altpersisch",
    ),
    (("per", "fas"), "fa", "Persian", "persan", "Persisch"),
    (
        "phi",
        None,
        "Philippine languages",
        "philippines, langues",
        "Philippinisch-Austronesisch (Andere)",
    ),
    ("phn", None, "Phoenician", "phénicien", "Phönikisch"),
    ("pli", "pi", "Pali", "pali", "Pali"),
    ("pol", "pl", "Polish", "polonais", "Polnisch"),
    ("pon", None, "Pohnpeian", "pohnpei", "Ponapeanisch"),
    ("por", "pt", "Portuguese", "portugais", "Portugiesisch"),
    ("pra", None, "Prakrit languages", "prâkrit, langues", "Prakrit"),
    (
        "pro",
        None,
        "Provençal, Old (to 1500);Occitan, Old (to 1500)",
        "provençal ancien (jusqu'à 1500); occitan ancien (jusqu'à 1500)",
        "Altokzitanisch",
    ),
    ("pus", "ps", "Pushto; Pashto", "pachto", "Paschtu"),
    (
        "qaa-qtz",
        None,
        "Reserved for local use",
        "réservée à l'usage local",
        "Reserviert für lokale Verwendung",
    ),
    ("que", "qu", "Quechua", "quechua", "Quechua-Sprache"),
    ("raj", None, "Rajasthani", "rajasthani", "Rajasthani"),
    ("rap", None, "Rapanui", "rapanui", "Osterinsel-Sprache"),
    (
        "rar",
        None,
        "Rarotongan; Cook Islands Maori",
        "rarotonga; maori des îles Cook",
        "Rarotonganisch",
    ),
    (
        "roa",
        None,
        "Romance languages",
        "romanes, langues",
        "Romanische Sprachen (Andere)",
    ),
    ("roh", "rm", "Romansh", "romanche", "Rätoromanisch"),
    ("rom", None, "Romany", "tsigane", "Romani (Sprache)"),
    (
        ("rum", "ron"),
        "ro",
        "Romanian; Moldavian; Moldovan",
        "roumain; moldave",
        "Rumänisch",
    ),
    (
        ("rum", "ron"),
        "ro",
        "Romanian; Moldavian; Moldovan",
        "roumain; moldave",
        "Rumänisch",
    ),
    ("run", "rn", "Rundi", "rundi", "Rundi-Sprache"),
    (
        "rup",
        None,
        "Aromanian; Arumanian; Macedo-Romanian",
        "aroumain; macédo-roumain",
        "Aromunisch",
    ),
    ("rus", "ru", "Russian", "russe", "Russisch"),
    ("sad", None, "Sandawe", "sandawe", "Sandawe-Sprache"),
    ("sag", "sg", "Sango", "sango", "Sango-Sprache"),
    ("sah", None, "Yakut", "iakoute", "Jakutisch"),
    (
        "sai",
        None,
        "South American Indian languages",
        "sud-amérindiennes, langues",
        "Indianersprachen, Südamerika (Andere)",
    ),
    ("sal", None, "Salishan languages", "salishennes, langues", "Salish-Sprache"),
    ("sam", None, "Samaritan Aramaic", "samaritain", "Samaritanisch"),
    ("san", "sa", "Sanskrit", "sanskrit", "Sanskrit"),
    ("sas", None, "Sasak", "sasak", "Sasak"),
    ("sat", None, "Santali", "santal", "Santali"),
    ("scn", None, "Sicilian", "sicilien", "Sizilianisch"),
    ("sco", None, "Scots", "écossais", "Schottisch"),
    ("sel", None, "Selkup", "selkoupe", "Selkupisch"),
    (
        "sem",
        None,
        "Semitic languages",
        "sémitiques, langues",
        "Semitische Sprachen (Andere)",
    ),
    ("sga", None, "Irish, Old (to 900)", "irlandais ancien (jusqu'à 900)", "Altirisch"),
    ("sgn", None, "Sign Languages", "langues des signes", "Zeichensprachen"),
    ("shn", None, "Shan", "chan", "Schan-Sprache"),
    ("sid", None, "Sidamo", "sidamo", "Sidamo-Sprache"),
    ("sin", "si", "Sinhala; Sinhalese", "singhalais", "Singhalesisch"),
    ("sio", None, "Siouan languages", "sioux, langues", "Sioux-Sprachen (Andere)"),
    (
        "sit",
        None,
        "Sino-Tibetan languages",
        "sino-tibétaines, langues",
        "Sinotibetische Sprachen (Andere)",
    ),
    ("sla", None, "Slavic languages", "slaves, langues", "Slawische Sprachen (Andere)"),
    (("slo", "slk"), "sk", "Slovak", "slovaque", "Slowakisch"),
    (("slo", "slk"), "sk", "Slovak", "slovaque", "Slowakisch"),
    ("slv", "sl", "Slovenian", "slovène", "Slowenisch"),
    ("sma", None, "Southern Sami", "sami du Sud", "Südsaamisch"),
    ("sme", "se", "Northern Sami", "sami du Nord", "Nordsaamisch"),
    ("smi", None, "Sami languages", "sames, langues", "Saamisch"),
    ("smj", None, "Lule Sami", "sami de Lule", "Lulesaamisch"),
    ("smn", None, "Inari Sami", "sami d'Inari", "Inarisaamisch"),
    ("smo", "sm", "Samoan", "samoan", "Samoanisch"),
    ("sms", None, "Skolt Sami", "sami skolt", "Skoltsaamisch"),
    ("sna", "sn", "Shona", "shona", "Schona-Sprache"),
    ("snd", "sd", "Sindhi", "sindhi", "Sindhi-Sprache"),
    ("snk", None, "Soninke", "soninké", "Soninke-Sprache"),
    ("sog", None, "Sogdian", "sogdien", "Sogdisch"),
    ("som", "so", "Somali", "somali", "Somali"),
    ("son", None, "Songhai languages", "songhai, langues", "Songhai-Sprache"),
    ("sot", "st", "Sotho, Southern", "sotho du Sud", "Süd-Sotho-Sprache"),
    ("spa", "es", "Spanish; Castilian", "espagnol; castillan", "Spanisch"),
    (("alb", "sqi"), "sq", "Albanian", "albanais", "Albanisch"),
    ("srd", "sc", "Sardinian", "sarde", "Sardisch"),
    ("srn", None, "Sranan Tongo", "sranan tongo", "Sranantongo"),
    ("srp", "sr", "Serbian", "serbe", "Serbisch"),
    ("srr", None, "Serer", "sérère", "Serer-Sprache"),
    (
        "ssa",
        None,
        "Nilo-Saharan languages",
        "nilo-sahariennes, langues",
        "Nilosaharanische Sprachen (Andere)",
    ),
    ("ssw", "ss", "Swati", "swati", "Swasi-Sprache"),
    ("suk", None, "Sukuma", "sukuma", "Sukuma-Sprache"),
    ("sun", "su", "Sundanese", "soundanais", "Sundanesisch"),
    ("sus", None, "Susu", "soussou", "Susu"),
    ("sux", None, "Sumerian", "sumérien", "Sumerisch"),
    ("swa", "sw", "Swahili (macrolanguage)", "swahili", "Swahili"),
    ("swe", "sv", "Swedish", "suédois", "Schwedisch"),
    ("syc", None, "Classical Syriac", "syriaque classique", "Syrisch"),
    ("syr", None, "Syriac", "syriaque", "Neuostaramäisch"),
    ("tah", "ty", "Tahitian", "tahitien", "Tahitisch"),
    ("tai", None, "Tai languages", "tai, langues", "Thaisprachen (Andere)"),
    ("tam", "ta", "Tamil", "tamoul", "Tamil"),
    ("tat", "tt", "Tatar", "tatar", "Tatarisch"),
    ("tel", "te", "Telugu", "télougou", "Telugu-Sprache"),
    ("tem", None, "Timne", "temne", "Temne-Sprache"),
    ("ter", None, "Tereno", "tereno", "Tereno-Sprache"),
    ("tet", None, "Tetum", "tetum", "Tetum-Sprache"),
    ("tgk", "tg", "Tajik", "tadjik", "Tadschikisch"),
    ("tgl", "tl", "Tagalog", "tagalog", "Tagalog"),
    ("tha", "th", "Thai", "thaï", "Thailändisch"),
    (("tib", "bod"), "bo", "Tibetan", "tibétain", "Tibetisch"),
    ("tig", None, "Tigre", "tigré", "Tigre-Sprache"),
    ("tir", "ti", "Tigrinya", "tigrigna", "Tigrinja-Sprache"),
    ("tiv", None, "Tiv", "tiv", "Tiv-Sprache"),
    ("tkl", None, "Tokelau", "tokelau", "Tokelauanisch"),
    ("tlh", None, "Klingon; tlhIngan-Hol", "klingon", "Klingonisch"),
    ("tli", None, "Tlingit", "tlingit", "Tlingit-Sprache"),
    ("tmh", None, "Tamashek", "tamacheq", "Tamašeq"),
    ("tog", None, "Tonga (Nyasa)", "tonga (Nyasa)", "Tonga (Bantusprache, Sambia)"),
    ("ton", "to", "Tonga (Tonga Islands)", "tongan (Îles Tonga)", "Tongaisch"),
    ("tpi", None, "Tok Pisin", "tok pisin", "Neumelanesisch"),
    ("tsi", None, "Tsimshian", "tsimshian", "Tsimshian-Sprache"),
    ("tsn", "tn", "Tswana", "tswana", "Tswana-Sprache"),
    ("tso", "ts", "Tsonga", "tsonga", "Tsonga-Sprache"),
    ("tuk", "tk", "Turkmen", "turkmène", "Turkmenisch"),
    ("tum", None, "Tumbuka", "tumbuka", "Tumbuka-Sprache"),
    ("tup", None, "Tupi languages", "tupi, langues", "Tupi-Sprache"),
    ("tur", "tr", "Turkish", "turc", "Türkisch"),
    (
        "tut",
        None,
        "Altaic languages",
        "altaïques, langues",
        "Altaische Sprachen (Andere)",
    ),
    ("tvl", None, "Tuvalu", "tuvalu", "Elliceanisch"),
    ("twi", "tw", "Twi", "twi", "Twi-Sprache"),
    ("tyv", None, "Tuvinian", "touva", "Tuwinisch"),
    ("udm", None, "Udmurt", "oudmourte", "Udmurtisch"),
    ("uga", None, "Ugaritic", "ougaritique", "Ugaritisch"),
    ("uig", "ug", "Uighur; Uyghur", "ouïgour", "Uigurisch"),
    ("ukr", "uk", "Ukrainian", "ukrainien", "Ukrainisch"),
    ("umb", None, "Umbundu", "umbundu", "Mbundu-Sprache"),
    ("und", None, "Undetermined", "indéterminée", "Nicht zu entscheiden"),
    ("urd", "ur", "Urdu", "ourdou", "Urdu"),
    ("uzb", "uz", "Uzbek", "ouszbek", "Usbekisch"),
    ("vai", None, "Vai", "vaï", "Vai-Sprache"),
    ("ven", "ve", "Venda", "venda", "Venda-Sprache"),
    ("vie", "vi", "Vietnamese", "vietnamien", "Vietnamesisch"),
    ("vol", "vo", "Volapük", "volapük", "Volapük"),
    ("vot", None, "Votic", "vote", "Wotisch"),
    ("wak", None, "Wakashan languages", "wakashanes, langues", "Wakash-Sprachen"),
    ("wal", None, "Wolaitta; Wolaytta", "wolaitta; wolaytta", "Walamo-Sprache"),
    ("war", None, "Waray", "waray", "Waray"),
    ("was", None, "Washo", "washo", "Washo-Sprache"),
    (("wel", "cym"), "cy", "Welsh", "gallois", "Kymrisch"),
    ("wen", None, "Sorbian languages", "sorabes, langues", "Sorbisch (Andere)"),
    ("wln", "wa", "Walloon", "wallon", "Wallonisch"),
    ("wol", "wo", "Wolof", "wolof", "Wolof-Sprache"),
    ("xal", None, "Kalmyk; Oirat", "kalmouk; oïrat", "Kalmückisch"),
    ("xho", "xh", "Xhosa", "xhosa", "Xhosa-Sprache"),
    ("yao", None, "Yao", "yao", "Yao-Sprache (Bantusprache)"),
    ("yap", None, "Yapese", "yapois", "Yapesisch"),
    ("yid", "yi", "Yiddish", "yiddish", "Jiddisch"),
    ("yor", "yo", "Yoruba", "yoruba", "Yoruba-Sprache"),
    ("ypk", None, "Yupik languages", "yupik, langues", "Ypik-Sprachen"),
    ("zap", None, "Zapotec", "zapotèque", "Zapotekisch"),
    (
        "zbl",
        None,
        "Blissymbols; Blissymbolics; Bliss",
        "symboles Bliss; Bliss",
        "Bliss-Symbol",
    ),
    ("zen", None, "Zenaga", "zenaga", "Zenaga"),
    ("zgh", None, "Standard Moroccan Tamazight", "amazighe standard marocain", ""),
    ("zha", "za", "Zhuang; Chuang", "zhuang; chuang", "Zhuang"),
    (("chi", "zho"), "zh", "Chinese", "chinois", "Chinesisch"),
    ("znd", None, "Zande languages", "zandé, langues", "Zande-Sprachen"),
    ("zul", "zu", "Zulu", "zoulou", "Zulu-Sprache"),
    ("zun", None, "Zuni", "zuni", "Zuñi-Sprache"),
    (
        "zxx",
        None,
        "No linguistic content; Not applicable",
        "pas de contenu linguistique; non applicable",
        "Kein linguistischer Inhalt",
    ),
    (
        "zza",
        None,
        "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki",
        "zaza; dimili; dimli; kirdki; kirmanjki; zazaki",
        "Zazaki",
    ),
]


#  a partial list of valid languages from the newer spec, with much more languages, seletec so that some models pass the language check
valid_iso_639_3_languages_list_partial: list[IsoLanguage] = [
    # see https://en.wikipedia.org/wiki/ISO_639:c
    ("cnh", None, ["Haka Chin", "Hakha Chin"], "", ""),
]
